### ISSUE TITLE
Will not Launch in 1.18, With no Other Mods Installed

### ISSUE THREAD

**Issue by praus1** [shedaniel/improved-stations#35]
I installed Improved Stations and Fabric API, no other mods. Game won’t launch. It’s fabric launcher 0.12.8.

This is the crash log I get: https://paste.atlauncher.com/view/bd9bbf6e-8a0d-4b07-ac73-177fee5e2a7e

**Comment by Chuunkyz** [comment]
[15:49:04] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/block/entity/BlockEntityClientSerializable
	at Not Enough Crashes deobfuscated stack trace.(1.18+build.1) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:601) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.8.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/block/entity/BlockEntityClientSerializable
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:218) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:156) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at me.shedaniel.istations.ImprovedStations.<clinit>(ImprovedStations.java:37) ~[improved-stations-2.0.7.jar:?]
	at net.minecraft.block.entity.BlockEntityType.handler$dej000$afterStaticInit(BlockEntityType:1536) ~[?:?]
	at net.minecraft.block.entity.BlockEntityType.<clinit>(BlockEntityType:62) ~[?:?]
	at net.minecraft.util.registry.Registry.method_10218(Registry:180) ~[?:?]
	at net.minecraft.util.registry.Registry.method_34031(Registry:278) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:277) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:49) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:153) ~[Fabric%201.18.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) ~[fabric-loader-0.12.8.jar:?]
	... 2 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.block.entity.BlockEntityClientSerializable
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.12.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:218) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:156) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at me.shedaniel.istations.ImprovedStations.<clinit>(ImprovedStations.java:37) ~[improved-stations-2.0.7.jar:?]
	at net.minecraft.block.entity.BlockEntityType.handler$dej000$afterStaticInit(BlockEntityType:1536) ~[?:?]
	at net.minecraft.block.entity.BlockEntityType.<clinit>(BlockEntityType:62) ~[?:?]
	at net.minecraft.util.registry.Registry.method_10218(Registry:180) ~[?:?]
	at net.minecraft.util.registry.Registry.method_34031(Registry:278) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:277) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:49) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:153) ~[Fabric%201.18.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) ~[fabric-loader-0.12.8.jar:?]
	... 2 more
